language: go
go:
    - 1.5
install:
    - export GOPATH=$GOPATH/src/github.com/gonet2/snowflake
    - cd $GOPATH
    - wget -qO- https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm | bash
    - go install snowflake
before_script:
script:
    - exit 0
